// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQQeWK9oppvfHHHbLexmlln_Wc3eWR0A',
    appId: '1:1096641068105:web:2460a6b182e318aa88d398',
    messagingSenderId: '1096641068105',
    projectId: 'flash-chat-1c437',
    authDomain: 'flash-chat-1c437.firebaseapp.com',
    storageBucket: 'flash-chat-1c437.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1B6XIsvZtlihNenUJlvzuNHo2EsfHZY',
    appId: '1:1096641068105:android:a1d295a357f4b4cc88d398',
    messagingSenderId: '1096641068105',
    projectId: 'flash-chat-1c437',
    storageBucket: 'flash-chat-1c437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6hqsqqX7iNQcrVWgEwFB5BqVEd3hYx8',
    appId: '1:1096641068105:ios:792776454cde7ff888d398',
    messagingSenderId: '1096641068105',
    projectId: 'flash-chat-1c437',
    storageBucket: 'flash-chat-1c437.appspot.com',
    iosClientId: '1096641068105-129k7p4d4djge5jtt4p4qt1fih81apgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF6hqsqqX7iNQcrVWgEwFB5BqVEd3hYx8',
    appId: '1:1096641068105:ios:55b2f881c433293a88d398',
    messagingSenderId: '1096641068105',
    projectId: 'flash-chat-1c437',
    storageBucket: 'flash-chat-1c437.appspot.com',
    iosClientId: '1096641068105-mqdv61cotuhahhaas63rc2d2tsb39h81.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
